openapi: 3.0.0
info:
  title: Carts API
  version: 1.0.0
paths:
  /api/carts:
    get:
      summary: Get all carts
      description: Show all carts
      operationId: getCarts
      responses:
        "200":
          description: A list of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"
    post:
      summary: Add a new cart
      description: Add new cart after create user
      operationId: addCart
      responses:
        "201":
          description: Cart added
  /api/carts/{cId}:
    get:
      summary: Get a cart by ID
      description: Show cart by ID
      operationId: getCartById
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "200":
          description: Cart details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    put:
      summary: Update a cart
      description: Update all cart by ID
      operationId: updateAllCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAllCart"
      responses:
        "200":
          description: Cart updated
    delete:
      summary: Delete a cart
      description: Delete cart by ID
      operationId: deleteCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "204":
          description: Cart deleted
  /api/carts/{cId}/products/{pId}:
    post:
      summary: Update a product in a cart
      description: Add product pId to cart cId
      operationId: updateCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
        - name: pId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "200":
          description: Product in cart updated
    delete:
      summary: Delete a product in a cart
      operationId: deleteProductInCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
        - name: pId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "204":
          description: Product in cart deleted
  /api/carts/{cId}/clear:
    post:
      summary: Clear a cart
      operationId: clearCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "200":
          description: Cart cleared
  /api/carts/{cId}/purchase:
    get:
      summary: Buy a cart
      operationId: buyCart
      parameters:
        - name: cId
          in: path
          required: true
          schema:
            type: string
            format: object-id
      responses:
        "200":
          description: Cart bought

components:
  schemas:
    Cart:
      type: object
      properties:
        products:
          type: array
          default: []
          items:
            type: object
            properties:
              productId:
                type: string
                format: object-id
              quantity:
                type: number
                default: 1
        uId:
          type: string
          format: object-id
          ref: users

    UpdateAllCart:
      type: object
      properties:
        products:
          type: array
          default: []
          items:
            type: object
            properties:
              productId:
                type: string
                format: object-id
              quantity:
                type: number
